<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>Blog Admin</title>
<!--[if IE]><script src="<?php echo $basePath; ?>/assets/lib/html5.js"></script><![endif]-->
<style>
@charset "utf-8";
/* CSS Document */

/*  Reset for some default browser CSS - General */
body, div, h1, h2, h3, p, ul, ol, li, img, header, section, aside, footer, button {
	margin: 0; padding: 0; border: 0; list-style: none;
}
article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}
#header {
	border-bottom:1px solid #ccc;
	height:50px;
	position:relative;
	padding-top:10px;
}
#header-left {
	left:0;top:10px;
	position:absolute;
	width:200px;
	height:30px;
	border:1px solid red;
}
#header-right {
	right:0;top:10px;
	position:absolute;
	width:200px;
	height:30px;
	border:1px solid red;
}
#header-center {
	height:40px;
	margin:0 205px;
	border:1px solid green;
}

</style>
</head>
<body>
	<header id="header">
		<div id="header-left"></div>
		<div id="header-center">
			<nav>
			
			<nav>
		</div>
		<div id="header-right"></div>
	</header>
	<div id="container">
	
	</div>
</body>
</html>